Sprint 9
santi-mgk/java-filmorate pull request #3
Opened 2022-12-11 14:36 UTC by santi-mgk

Сделано задание по спринту 9

2022-12-12 10:11 UTC, kalitva requested changes

2022-12-12 10:11 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private int duration;
Уточни в названии в чем будет измеряться длительность, в минутах или секундах

2022-12-12 10:11 UTC, kalitva commented on src/main/resources/application.properties
> +logging.level.ru.yandex.practicum.filmorate=error
Лучше установи левел debug

2022-12-13 18:24 UTC, santi-mgk commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            log.error("Name film is empty.");
Я правильно понял, в данном случае надо проверки обернуть в try catch и  логирование положить в блок catch ?

2022-12-13 18:27 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            log.error("Name film is empty.");
Нет, не надо try catch, перехватывать исключения будем в следующих спринтах, там и залогируем

2022-12-13 18:51 UTC, santi-mgk commented on src/main/java/ru/yandex/practicum/filmorate/FilmorateApplication.java
> +package ru.yandex.practicum.filmorate;
Я помню что в официальном источнике написано что вместо таба, при написании кода, необходимо использовать пробелы. Действительно ли это так важно? Я к тому что, использование пробелов, как мне кажется, замедляет скорость разработки. И если я сейчас напишу 4 пробела и попробую их стереть, то они сотрутся все одним разом, как стёрся бы таб.

2022-12-13 19:02 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/FilmorateApplication.java
> +package ru.yandex.practicum.filmorate;
Да, это важно. Но не из-за скорости разработки (на которую это на самом деле никак не влияет), а из-за потенциальной путаницы с форматированием. Правило такое: если в проекте используются табы ,нужно использовать везде только табы, если пробелы, то везде пробелы

2022-12-15 07:30 UTC, santi-mgk commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private int duration;
Если уточню, не будут проходить тесты. Оставил название duration

2022-12-15 16:33 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film.getName().isBlank() || film.getName().isEmpty()) {
Удали проверку, `@NotBlank` уже валидирует, что значение не будет пустым

2022-12-15 16:36 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (user.getId() == 0) {
А зачем проверка, в любом случае при создании нужно сетнуть новый айди

2022-12-15 16:41 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    @NotBlank(message = "Отсутствует email")
`@NotBlank` лишнее, а вот null рассматривается как валидный емэйл, следует поставить `@NotNull`

2022-12-15 16:43 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private void validate(User user) {
Удали все проверки, которые уже делают аннотации

2022-12-15 16:44 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +            user.setName(user.getLogin());
Это не относится к логике валидации, верни обратно из этого метода

2022-12-15 16:46 UTC, kalitva commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +    private String fillString(int count,char c) {
Взгляни на метод `String#repeat`

2022-12-15 16:50 UTC, kalitva commented on pom.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Почему не сделал? Это пара кликов в IDE

2022-12-21 12:47 UTC, santi-mgk commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film.getName().isBlank() || film.getName().isEmpty()) {
Я могу выкидывать исключения в аннотациях? Без исключений тесты не проходят и я не могу сдать дз

2022-12-21 16:38 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film.getName().isBlank() || film.getName().isEmpty()) {
Странно, отправляй дз, потом разберемся. И лучше пиши в чате в таких случаях, почту не всегда мониторю

2022-12-22 16:58 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film.getName().isBlank() || film.getName().isEmpty()) {
Не проходят твои тесты  контроллеров, а не постмановские . Сделай так, чтобы твои юнит тесты проходили - удали проверки валидаций, которые перенес в аннотации и будет окей

2022-12-25 08:51 UTC, merged

2022-12-25 10:03 UTC, santi-mgk commented
Случайно закрыл этот пулл реквест.
Я, пока, так и не понял, почему у меня в тестах аннотации не срабатывают и фильмы/пользователи создаются без проблем.